services:
    wobblecode.restbundle.param_converter.jms_serializer:
        class: WobbleCode\RestBundle\Request\ParamConverter\JMSSerializerParamConverter
        tags:
            - { name: request.param_converter, converter: jms_serializer }
        arguments:
            - "@jms_serializer.serializer"
    wobblecode.restbundle.listener.controller:
        class: WobbleCode\RestBundle\EventListener\ControllerListener
        arguments:
            - "@annotation_reader"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    wobblecode.restbundle.rest_suscriber:
        class: WobbleCode\RestBundle\EventListener\RestSubscriber
        arguments:
            - "@jms_serializer.serializer"
        tags:
            - { name: kernel.event_subscriber }
